name = "SpidersMessageEncoding"
uuid = "25d647a0-ef7d-4da3-8ba8-11abaa3d526c"
author = "William Thompson"
version = "3.0.0"

[deps]
SimpleBinaryEncoding = "165d4630-7e21-4626-b3c2-016fbf5108c4"
StaticStrings = "4db0a0c5-418a-4e1d-8806-cb305fe13294"

[compat]
SimpleBinaryEncoding = "3"
StaticStrings = "0.2"